/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.proyecto;

import java.awt.event.ActionEvent;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author usuario
 */
public class createdialog extends javax.swing.JDialog {

    /**
     * Creates new form createdialog
     */
    public createdialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ActionEvent evt = null;
        
        ConfLocActionPerformed(evt);
        ConfVisActionPerformed(evt);
        EquipoVisActionPerformed(evt);
        EquipoLocActionPerformed(evt);
    }

    int codigo;
    String confl;
    String confv;
    String equipoL;
    String equipoV;
    int puntosL;
    int puntosV;
    String temporada;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ConfVis = new javax.swing.JComboBox<>();
        ConfLoc = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        EquipoLoc = new javax.swing.JComboBox<>();
        EquipoVis = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Codigo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Temporada = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        PuntosVis = new javax.swing.JTextField();
        PuntosLoc = new javax.swing.JTextField();
        CrearJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Equipo Visitante");

        ConfVis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "East", "West" }));
        ConfVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfVisActionPerformed(evt);
            }
        });

        ConfLoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "East", "Wes" }));
        ConfLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfLocActionPerformed(evt);
            }
        });

        jLabel6.setText("Conferencia");

        jLabel7.setText("Equipo");

        EquipoLoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "76ers" }));
        EquipoLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoLocActionPerformed(evt);
            }
        });

        EquipoVis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "76ers" }));
        EquipoVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoVisActionPerformed(evt);
            }
        });

        jLabel8.setText("Equipo local");

        jLabel9.setText("Código");

        Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoActionPerformed(evt);
            }
        });

        jLabel10.setText("Temporada");

        Temporada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemporadaActionPerformed(evt);
            }
        });

        jLabel11.setText("Puntos");

        PuntosVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuntosVisActionPerformed(evt);
            }
        });

        PuntosLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuntosLocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Temporada, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(ConfLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfVis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(EquipoLoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EquipoVis, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PuntosVis, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PuntosLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(78, 78, 78))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(EquipoLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EquipoVis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PuntosVis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ConfVis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(PuntosLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(ConfLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(Temporada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        CrearJButton.setText("Crear partido");
        CrearJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CrearJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cancelar))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 565, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar)
                    .addComponent(CrearJButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void ConfVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfVisActionPerformed
        // TODO add your handling code here:
        String confv = ConfVis.getSelectedItem().toString();

        Connection con; //declaramos las variables necesarias.
        Statement sentencia;
        String sql;
        ResultSet rs;
        //Recogemos la información de confi
        String ip = "";
        String usuario = "";
        String contraseña = "";
        String Driver = "";
        String Puerto = "";
        String bdd = "";
        try (ObjectInputStream flujoEntrada = new ObjectInputStream(new FileInputStream("src\\main\\java\\com\\mycompany\\proyecto\\config.ini")) {
        }) {

            try {
                ip = (String) flujoEntrada.readObject();
                usuario = (String) flujoEntrada.readObject();
                contraseña = (String) flujoEntrada.readObject();
                Driver = (String) flujoEntrada.readObject();
                Puerto = (String) flujoEntrada.readObject();
                bdd = (String) flujoEntrada.readObject();
            } catch (IOException e) {
                System.out.println(e);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException e) {
            System.out.println(e);
        }

        String url = "jdbc:mysql://" + ip + ":" + Puerto + "/" + bdd;

        List<String> equipos_conf = new ArrayList<>();
        if (confv.equals("East")) {

            try {
                con = DriverManager.getConnection(url, usuario, contraseña);

                sql = "SELECT nombre FROM equipos WHERE conferencia = 'East'";
                sentencia = (Statement) con.createStatement();
                rs = sentencia.executeQuery(sql);

                while (rs.next()) {
                    String a = rs.getString("nombre");
                    equipos_conf.add(a);
                }
            } catch (SQLException e) {
                Logger.getLogger(Proyecto.class.getName()).log(Level.SEVERE, null, e);
            }

            String wiiii[] = equipos_conf.toArray(new String[0]);

            DefaultComboBoxModel e = new DefaultComboBoxModel(wiiii);

            EquipoVis.setModel(e);

        } else {
            try {
                con = DriverManager.getConnection(url, usuario, contraseña);

                sql = "SELECT nombre FROM equipos WHERE conferencia = 'West'";
                sentencia = (Statement) con.createStatement();
                rs = sentencia.executeQuery(sql);

                while (rs.next()) {
                    String a = rs.getString("nombre");
                    equipos_conf.add(a);
                }
            } catch (SQLException e) {
                Logger.getLogger(Proyecto.class.getName()).log(Level.SEVERE, null, e);
            }

            String wiiii[] = equipos_conf.toArray(new String[0]);

            DefaultComboBoxModel e = new DefaultComboBoxModel(wiiii);

            EquipoVis.setModel(e);
        }
        EquipoVisActionPerformed(evt);
    }//GEN-LAST:event_ConfVisActionPerformed

    private void ConfLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfLocActionPerformed
        // TODO add your handling code here:
        confl = ConfLoc.getSelectedItem().toString();

        Connection con; //declaramos las variables necesarias.
        Statement sentencia;
        String sql;
        ResultSet rs;
        //Recogemos la información de confi
        String ip = "";
        String usuario = "";
        String contraseña = "";
        String Driver = "";
        String Puerto = "";
        String bdd = "";
        try (ObjectInputStream flujoEntrada = new ObjectInputStream(new FileInputStream("src\\main\\java\\com\\mycompany\\proyecto\\config.ini")) {
        }) {

            try {
                ip = (String) flujoEntrada.readObject();
                usuario = (String) flujoEntrada.readObject();
                contraseña = (String) flujoEntrada.readObject();
                Driver = (String) flujoEntrada.readObject();
                Puerto = (String) flujoEntrada.readObject();
                bdd = (String) flujoEntrada.readObject();
            } catch (IOException e) {
                System.out.println(e);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException e) {
            System.out.println(e);
        }

        String url = "jdbc:mysql://" + ip + ":" + Puerto + "/" + bdd;

        List<String> equipos_conf = new ArrayList<>();
        if (confl.equals("East")) {

            try {
                con = DriverManager.getConnection(url, usuario, contraseña);

                sql = "SELECT nombre FROM equipos WHERE conferencia = 'East'";
                sentencia = (Statement) con.createStatement();
                rs = sentencia.executeQuery(sql);

                while (rs.next()) {
                    String a = rs.getString("nombre");
                    equipos_conf.add(a);
                }
            } catch (SQLException e) {
                Logger.getLogger(Proyecto.class.getName()).log(Level.SEVERE, null, e);
            }

            String wiiii[] = equipos_conf.toArray(new String[0]);

            DefaultComboBoxModel e = new DefaultComboBoxModel(wiiii);

            EquipoLoc.setModel(e);

        } else {
            try {
                con = DriverManager.getConnection(url, usuario, contraseña);

                sql = "SELECT nombre FROM equipos WHERE conferencia = 'West'";
                sentencia = (Statement) con.createStatement();
                rs = sentencia.executeQuery(sql);

                while (rs.next()) {
                    String a = rs.getString("nombre");
                    equipos_conf.add(a);
                }
            } catch (SQLException e) {
                Logger.getLogger(Proyecto.class.getName()).log(Level.SEVERE, null, e);
            }

            String wiiii[] = equipos_conf.toArray(new String[0]);

            DefaultComboBoxModel e = new DefaultComboBoxModel(wiiii);

            EquipoLoc.setModel(e);

        }
        EquipoLocActionPerformed(evt);
    }//GEN-LAST:event_ConfLocActionPerformed

    private void EquipoLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoLocActionPerformed
        // TODO add your handling code here:
        equipoL = EquipoLoc.getSelectedItem().toString();
    }//GEN-LAST:event_EquipoLocActionPerformed

    private void EquipoVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoVisActionPerformed
        // TODO add your handling code here:
        equipoV = EquipoVis.getSelectedItem().toString();
    }//GEN-LAST:event_EquipoVisActionPerformed

    private void CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoActionPerformed

    private void TemporadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemporadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TemporadaActionPerformed

    private void PuntosVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuntosVisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PuntosVisActionPerformed

    private void PuntosLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuntosLocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PuntosLocActionPerformed

    private void CrearJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearJButtonActionPerformed
        // TODO add your handling code here:

        //"INSERT INTO partidos VALUES ("+codigo+",'"+equipoL+"','"+equipoV+"',"+puntosL+","puntosV+",'"+temporada"');"
        Connection con; //declaramos las variables necesarias.
        Statement sentencia;
        String sql;
        ResultSet rs;
        //Recogemos la información de confi
        String ip = "";
        String usuario = "";
        String contraseña = "";
        String Driver = "";
        String Puerto = "";
        String bdd = "";
        try (ObjectInputStream flujoEntrada = new ObjectInputStream(new FileInputStream("src\\main\\java\\com\\mycompany\\proyecto\\config.ini")) {
        }) {

            try {
                ip = (String) flujoEntrada.readObject();
                usuario = (String) flujoEntrada.readObject();
                contraseña = (String) flujoEntrada.readObject();
                Driver = (String) flujoEntrada.readObject();
                Puerto = (String) flujoEntrada.readObject();
                bdd = (String) flujoEntrada.readObject();
            } catch (IOException e) {
                System.out.println(e);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException e) {
            System.out.println(e);
        }

        String url = "jdbc:mysql://" + ip + ":" + Puerto + "/" + bdd;

        try {

            //lo pedido en cuestion
            con = DriverManager.getConnection(url, usuario, contraseña);
            codigo = Integer.parseInt(Codigo.getText());
            puntosL = Integer.parseInt(PuntosLoc.getText());
            puntosV = Integer.parseInt(PuntosVis.getText());
            temporada = Temporada.getText();
            sql = "INSERT INTO partidos VALUES (" + codigo + ",'" + equipoL + "','" + equipoV + "'," + puntosL + "," + puntosV + ",'" + temporada + "');";

            System.out.println(sql);
            //sql = "SELECT * FROM partidos WHERE equipo_local = 'Raptors';";
            sentencia = (Statement) con.createStatement();
            sentencia.executeUpdate(sql);

        } catch (SQLException e) {
            Logger.getLogger(Proyecto.class.getName()).log(Level.SEVERE, null, e);
        }

        this.dispose();
    }//GEN-LAST:event_CrearJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                createdialog dialog = new createdialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextField Codigo;
    private javax.swing.JComboBox<String> ConfLoc;
    private javax.swing.JComboBox<String> ConfVis;
    private javax.swing.JButton CrearJButton;
    private javax.swing.JComboBox<String> EquipoLoc;
    private javax.swing.JComboBox<String> EquipoVis;
    private javax.swing.JTextField PuntosLoc;
    private javax.swing.JTextField PuntosVis;
    private javax.swing.JTextField Temporada;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
