/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/*
bd      =nba
user    =root
pass    =
ip      =localhost
puerto  =3306
driver  =com.mysql.jdbc.Driver;

 */
/**
 *
 * @author usuario
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        try {
            String filepath = "src\\main\\java\\com\\mycompany\\proyecto\\config.ini";
            File file = new File(filepath);

            boolean exists = file.exists();
            if (exists) {
                mostrarValoresconfigurados();
            }
        } catch (Exception e) {
            System.out.println(e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        IPjTextField = new javax.swing.JTextField();
        UsuariojTextField = new javax.swing.JTextField();
        ContraseñajTextField = new javax.swing.JTextField();
        PuertojTextField = new javax.swing.JTextField();
        DriverjTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BaseDeDatosjTextField = new javax.swing.JTextField();
        ContinuarjButton = new javax.swing.JButton();
        AceptarjButton = new javax.swing.JButton();
        AplicarjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configuración de datos de conexión");

        jLabel1.setText("IP");

        jLabel2.setText("usuario");

        jLabel3.setText("contraseña");

        jLabel4.setText("Puerto");

        jLabel5.setText("Base de datos");

        IPjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IPjTextFieldActionPerformed(evt);
            }
        });

        DriverjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DriverjTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Driver");

        BaseDeDatosjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaseDeDatosjTextFieldActionPerformed(evt);
            }
        });

        ContinuarjButton.setText("Continuar");

        AceptarjButton.setText("Aceptar");
        AceptarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarjButtonActionPerformed(evt);
            }
        });

        AplicarjButton.setText("Aplicar");
        AplicarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AplicarjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(IPjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel1)))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(UsuariojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PuertojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(DriverjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(ContraseñajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(BaseDeDatosjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AplicarjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AceptarjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ContinuarjButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IPjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsuariojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContraseñajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DriverjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PuertojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BaseDeDatosjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContinuarjButton)
                    .addComponent(AceptarjButton)
                    .addComponent(AplicarjButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IPjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IPjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IPjTextFieldActionPerformed

    private void DriverjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DriverjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DriverjTextFieldActionPerformed

    private void BaseDeDatosjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaseDeDatosjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BaseDeDatosjTextFieldActionPerformed

    private void AplicarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AplicarjButtonActionPerformed
        // TODO add your handling code here:
        ObjectOutputStream flujosalida = null;

        try {
            String ip = IPjTextField.getText() + "";
            String usuario = UsuariojTextField.getText() + "";
            String contraseña = ContraseñajTextField.getText() + "";
            String Driver = DriverjTextField.getText() + "";
            String Puerto = PuertojTextField.getText() + "";
            String bdd = BaseDeDatosjTextField.getText() + "";

            flujosalida = new ObjectOutputStream(new FileOutputStream("src\\main\\java\\com\\mycompany\\proyecto\\config.ini"));
            flujosalida.writeObject(ip);
            flujosalida.writeObject(usuario);
            flujosalida.writeObject(contraseña);
            flujosalida.writeObject(Driver);
            flujosalida.writeObject(Puerto);
            flujosalida.writeObject(bdd);

        } catch (IOException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        } finally {
            JOptionPane.showMessageDialog(rootPane, "Cambios aplicados");
            System.out.println("trabajo terminado");
            if (flujosalida != null) {
                try {
                    flujosalida.close();
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(rootPane, e);
                }
            }
        }
    }//GEN-LAST:event_AplicarjButtonActionPerformed

    private void AceptarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarjButtonActionPerformed
        // TODO add your handling code here:
        AplicarjButtonActionPerformed(evt);
        mainframe mf = new mainframe();
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AceptarjButtonActionPerformed

    private void mostrarValoresconfigurados() {
        try (ObjectInputStream flujoEntrada = new ObjectInputStream(new FileInputStream("src\\main\\java\\com\\mycompany\\proyecto\\config.ini")) {
        }) {
            String ip = "";
            String usuario = "";
            String contraseña = "";
            String Driver = "";
            String Puerto = "";
            String bdd = "";
            try {
                ip = (String) flujoEntrada.readObject();
                usuario = (String) flujoEntrada.readObject();
                contraseña = (String) flujoEntrada.readObject();
                Driver = (String) flujoEntrada.readObject();
                Puerto = (String) flujoEntrada.readObject();
                bdd = (String) flujoEntrada.readObject();
            } catch (IOException e) {
                System.out.println(e);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Formulario.class.getName()).log(Level.SEVERE, null, ex);
            }
            IPjTextField.setText(ip);
            UsuariojTextField.setText(usuario);
            ContraseñajTextField.setText(contraseña);
            DriverjTextField.setText(Driver);
            PuertojTextField.setText(Puerto);
            BaseDeDatosjTextField.setText(bdd);
        } catch (IOException e) {
            System.out.println(e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);

            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarjButton;
    private javax.swing.JButton AplicarjButton;
    private javax.swing.JTextField BaseDeDatosjTextField;
    private javax.swing.JButton ContinuarjButton;
    private javax.swing.JTextField ContraseñajTextField;
    private javax.swing.JTextField DriverjTextField;
    private javax.swing.JTextField IPjTextField;
    private javax.swing.JTextField PuertojTextField;
    private javax.swing.JTextField UsuariojTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
