/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.collecejs;
import java.util.*;
/**
 *
 * @author isaye
 */
public class Ejercicio14 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio14
     */
    private Map<String, Integer> mapaPalabras = new HashMap<>();
    public Ejercicio14() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public String toString (Map<String, Integer> mapa)
    {
        String cad = "";
        
        for (Map.Entry<String, Integer> entry : mapa.entrySet())
        {
            String palabra = entry.getKey();
            Integer frecuencia = entry.getValue();
            cad = cad + palabra + " ->" + frecuencia + ";";
        }
        
        return cad;
    }
    public String toString (List <String> lista)
    {
        String cad= "";
        Iterator <String> it = lista.iterator();
        for(;it.hasNext();)
        {
            String palabra = it.next();
            cad = cad + " " + palabra;
        }
        return cad;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonRetorno = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        salidaNumImp3 = new javax.swing.JScrollPane();
        salidaMapa = new javax.swing.JTextArea();
        salidaNumImp4 = new javax.swing.JScrollPane();
        salidaPalabrasFrecuencia = new javax.swing.JTextArea();
        salidaNumImp5 = new javax.swing.JScrollPane();
        entradaPalabras = new javax.swing.JTextArea();
        salidaNumImp6 = new javax.swing.JScrollPane();
        entradaFrecuencia = new javax.swing.JTextArea();
        botonAnadir = new javax.swing.JButton();
        botonBuscarFrecuencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonRetorno.setText("Volver al menú Principal");
        BotonRetorno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRetornoMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Ejercicio 14");

        salidaMapa.setColumns(20);
        salidaMapa.setRows(5);
        salidaNumImp3.setViewportView(salidaMapa);

        salidaPalabrasFrecuencia.setColumns(20);
        salidaPalabrasFrecuencia.setRows(5);
        salidaNumImp4.setViewportView(salidaPalabrasFrecuencia);

        entradaPalabras.setColumns(20);
        entradaPalabras.setRows(5);
        salidaNumImp5.setViewportView(entradaPalabras);

        entradaFrecuencia.setColumns(20);
        entradaFrecuencia.setRows(5);
        salidaNumImp6.setViewportView(entradaFrecuencia);

        botonAnadir.setText("Añadir Palabra");
        botonAnadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAnadirMouseClicked(evt);
            }
        });

        botonBuscarFrecuencia.setText("Buscar Frecuencia");
        botonBuscarFrecuencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBuscarFrecuenciaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BotonRetorno))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(salidaNumImp6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonBuscarFrecuencia))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(salidaNumImp4, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(salidaNumImp5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(botonAnadir))
                                .addComponent(salidaNumImp3, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(salidaNumImp5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonAnadir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(salidaNumImp3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(salidaNumImp6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonBuscarFrecuencia)))
                .addGap(18, 18, 18)
                .addComponent(salidaNumImp4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(BotonRetorno)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRetornoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRetornoMouseClicked
        // TODO add your handling code here:
        MenuPrincipal abrir = new MenuPrincipal();
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonRetornoMouseClicked

    private void botonAnadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAnadirMouseClicked
        // TODO add your handling code here:
        String palabra = entradaPalabras.getText();
        
        if (this.mapaPalabras.containsKey(palabra))
            {
                //actualizar el valor de la frecuencia
                Integer valor = this.mapaPalabras.get(palabra);
                valor++;
                this.mapaPalabras.put(palabra, valor);
            }
            else
            {
                //añadir la nueva palabra
                this.mapaPalabras.put(palabra, 1);
            }
        salidaMapa.setText(toString(this.mapaPalabras));
    }//GEN-LAST:event_botonAnadirMouseClicked

    private void botonBuscarFrecuenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBuscarFrecuenciaMouseClicked
        // TODO add your handling code here:
        //leer el numero y pasarlo a int
        String num = entradaFrecuencia.getText();
        int numero = Integer.parseInt(num);
        
        //invertir los valores y key del mapa
        //mapa nuevo para rellenar con los valores y key invertidos
        Map <Integer, String> mapaFrecuencia = new HashMap<>();
        //iterador para el primer mapa
        for (Map.Entry<String, Integer> entry : this.mapaPalabras.entrySet())
        {
            String palabra = entry.getKey();
            Integer frecuencia = entry.getValue();
            if(mapaFrecuencia.containsKey(frecuencia))
            {
                String contenido = mapaFrecuencia.get(frecuencia);
                palabra = palabra + " " + contenido;
                mapaFrecuencia.put(frecuencia, palabra);
            }
            //frecuenciaPalabrasInverso.put(frec, word);
            mapaFrecuencia.put(frecuencia, palabra);
        }
        
        //añadir los valores de los key que se correspondan con numero a una lista
        List <String> lista = new ArrayList();
        for (Map.Entry<Integer, String> entry2 : mapaFrecuencia.entrySet())
        {
            Integer frecuencia = entry2.getKey();
            if(frecuencia == numero)
            {
                String palabra = entry2.getValue();
                lista.add(palabra);
            }
        }
        
        salidaPalabrasFrecuencia.setText(toString(lista));
        
    }//GEN-LAST:event_botonBuscarFrecuenciaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio14().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRetorno;
    private javax.swing.JButton botonAnadir;
    private javax.swing.JButton botonBuscarFrecuencia;
    private javax.swing.JTextArea entradaFrecuencia;
    private javax.swing.JTextArea entradaPalabras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextArea salidaMapa;
    private javax.swing.JScrollPane salidaNumImp3;
    private javax.swing.JScrollPane salidaNumImp4;
    private javax.swing.JScrollPane salidaNumImp5;
    private javax.swing.JScrollPane salidaNumImp6;
    private javax.swing.JTextArea salidaPalabrasFrecuencia;
    // End of variables declaration//GEN-END:variables
}
