/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.collecejs;

/**
 *
 * @author usuario
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        EjList = new javax.swing.JLabel();
        Ej2 = new javax.swing.JButton();
        Ej1 = new javax.swing.JButton();
        Ej3 = new javax.swing.JButton();
        Ej4 = new javax.swing.JButton();
        Ej5 = new javax.swing.JButton();
        Ej6 = new javax.swing.JButton();
        Ej7 = new javax.swing.JButton();
        Ej8 = new javax.swing.JButton();
        Ej9 = new javax.swing.JButton();
        Ej10 = new javax.swing.JButton();
        Ej11 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        EjSet = new javax.swing.JLabel();
        Ej12 = new javax.swing.JButton();
        Ej13 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        EjMap = new javax.swing.JLabel();
        Ej14 = new javax.swing.JButton();
        Ej15 = new javax.swing.JButton();
        Ej16 = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        EjList.setText("Ejercicios List");

        Ej2.setText("Ejercicio 2");
        Ej2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ej2ActionPerformed(evt);
            }
        });

        Ej1.setText("Ejercicio 1");
        Ej1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ej1ActionPerformed(evt);
            }
        });

        Ej3.setText("Ejercicio 3");
        Ej3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ej3ActionPerformed(evt);
            }
        });

        Ej4.setText("Ejercicio 4");
        Ej4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ej4ActionPerformed(evt);
            }
        });

        Ej5.setText("Ejercicio 5");
        Ej5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ej5ActionPerformed(evt);
            }
        });

        Ej6.setText("Ejercicio 6");
        Ej6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ej6ActionPerformed(evt);
            }
        });

        Ej7.setText("Ejercicio 7");
        Ej7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ej7ActionPerformed(evt);
            }
        });

        Ej8.setText("Ejercicio 8");
        Ej8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ej8ActionPerformed(evt);
            }
        });

        Ej9.setText("Ejercicio 9");
        Ej9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ej9ActionPerformed(evt);
            }
        });

        Ej10.setText("Ejercicio 10");
        Ej10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ej10ActionPerformed(evt);
            }
        });

        Ej11.setText("Ejercicio 11");
        Ej11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ej11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EjList)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Ej1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ej2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ej3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ej4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Ej5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ej6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ej7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ej8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Ej9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ej10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ej11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EjList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ej1)
                    .addComponent(Ej2)
                    .addComponent(Ej3)
                    .addComponent(Ej4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ej5)
                    .addComponent(Ej6)
                    .addComponent(Ej7)
                    .addComponent(Ej8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ej9)
                    .addComponent(Ej10)
                    .addComponent(Ej11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        EjSet.setText("Ejercicios Set");

        Ej12.setText("Ejercicio 12");
        Ej12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ej12ActionPerformed(evt);
            }
        });

        Ej13.setText("Ejercicio 13");
        Ej13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ej13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EjSet)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Ej12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ej13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EjSet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ej12)
                    .addComponent(Ej13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        EjMap.setText("Ejercicios Map");

        Ej14.setText("Ejercicio 14");
        Ej14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ej14ActionPerformed(evt);
            }
        });

        Ej15.setText("Ejercicio 15");
        Ej15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ej15ActionPerformed(evt);
            }
        });

        Ej16.setText("Ejercicio 16");
        Ej16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ej16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EjMap)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Ej14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ej15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ej16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EjMap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ej14)
                    .addComponent(Ej15)
                    .addComponent(Ej16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ej1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ej1ActionPerformed
        // TODO add your handling code here:
        Ej01 ej1 =  new Ej01();
        ej1.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_Ej1ActionPerformed

    private void Ej2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ej2ActionPerformed
        // TODO add your handling code here:
        Ej02 ej2 =  new Ej02();
        ej2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Ej2ActionPerformed

    private void Ej3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ej3ActionPerformed
        // TODO add your handling code here:
        Ej03 ej3 =  new Ej03();
        ej3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Ej3ActionPerformed

    private void Ej4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ej4ActionPerformed
        // TODO add your handling code here:
        Ej04 ej4 =  new Ej04();
        ej4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Ej4ActionPerformed

    private void Ej11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ej11ActionPerformed
        // TODO add your handling code here:
        Ej11 ej11 =  new Ej11();
        ej11.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Ej11ActionPerformed

    private void Ej5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ej5ActionPerformed
        // TODO add your handling code here:
        Ej05 ej5 =  new Ej05();
        ej5.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Ej5ActionPerformed

    private void Ej6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ej6ActionPerformed
        // TODO add your handling code here:
        Ej06 ej6 =  new Ej06();
        ej6.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Ej6ActionPerformed

    private void Ej7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ej7ActionPerformed
        // TODO add your handling code here:
        Ej07 ej7 =  new Ej07();
        ej7.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Ej7ActionPerformed

    private void Ej8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ej8ActionPerformed
        // TODO add your handling code here:
        Ej08 ej8 =  new Ej08();
        ej8.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Ej8ActionPerformed

    private void Ej10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ej10ActionPerformed
        // TODO add your handling code here:
        Ej10 ej10 =  new Ej10();
        ej10.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_Ej10ActionPerformed

    private void Ej9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ej9ActionPerformed
        // TODO add your handling code here:
        Ej09 ej9 =  new Ej09();
        ej9.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_Ej9ActionPerformed

    private void Ej12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ej12ActionPerformed
        // TODO add your handling code here:
        Ej12 ej12 =  new Ej12();
        ej12.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Ej12ActionPerformed

    private void Ej13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ej13ActionPerformed
        // TODO add your handling code here:
        Ej13 ej13 =  new Ej13();
        ej13.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Ej13ActionPerformed

    private void Ej14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ej14ActionPerformed
        // TODO add your handling code here:
        Ej14 ej14 =  new Ej14();
        ej14.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Ej14ActionPerformed

    private void Ej15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ej15ActionPerformed
        // TODO add your handling code here:
        Ej15 ej15 =  new Ej15();
        ej15.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Ej15ActionPerformed

    private void Ej16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ej16ActionPerformed
        // TODO add your handling code here:
        Ej16 ej16 =  new Ej16();
        ej16.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Ej16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ej1;
    private javax.swing.JButton Ej10;
    private javax.swing.JButton Ej11;
    private javax.swing.JButton Ej12;
    private javax.swing.JButton Ej13;
    private javax.swing.JButton Ej14;
    private javax.swing.JButton Ej15;
    private javax.swing.JButton Ej16;
    private javax.swing.JButton Ej2;
    private javax.swing.JButton Ej3;
    private javax.swing.JButton Ej4;
    private javax.swing.JButton Ej5;
    private javax.swing.JButton Ej6;
    private javax.swing.JButton Ej7;
    private javax.swing.JButton Ej8;
    private javax.swing.JButton Ej9;
    private javax.swing.JLabel EjList;
    private javax.swing.JLabel EjMap;
    private javax.swing.JLabel EjSet;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
